services:
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - monitoring_network

  loki:
    image: grafana/loki:latest
    container_name: monitoring_loki
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    user: root
    ports:
      - "4317:4317"
    volumes:
      - ./monitoring/alloy-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring_network

networks:
  monitoring_network:
    external: true