name: Deploy Monitoring
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.1

      - name: Create .env file
        shell: bash
        run: |
          $envContent = @"
          ${{ secrets.ENV_FILE }}
          "@
          [System.IO.File]::WriteAllLines("$pwd\.env", $envContent)

      - name: Build and Restart
        run: |
          just up